import { useEffect, useState } from "react";
import { Search, Trash2, RefreshCw } from "lucide-react";
import { useTranslation } from "react-i18next";
import { adminApi } from "../../lib/api";

export default function AdminUsers(){
 const {t}=useTranslation(); const [users,setUsers]=useState<any[]>([]); const [q,setQ]=useState(""); const [status,setStatus]=useState(""); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await adminApi.users({q,status,page,limit:12});setUsers(r.users);setPages(r.pages)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[page,status]); 
 const change=async(id:string,s:string)=>{if(!window.confirm(t("admin.users.confirmStatus")) )return;await adminApi.userStatus(id,s);void load()};
 const del=async(id:string)=>{if(!window.confirm(t("admin.users.confirmDelete")))return;await adminApi.deleteUser(id);void load()};
 return <div><div className="gls-admin-page-title"><div><p>{t("admin.nav.users")}</p><h1>{t("admin.users.title")}</h1><span>{t("admin.users.subtitle")}</span></div><button onClick={()=>void load()} className="gls-admin-refresh"><RefreshCw size={16}/>{t("admin.common.refresh")}</button></div>
 <section className="gls-admin-card-v2"><div className="gls-admin-toolbar"><div className="gls-admin-searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setPage(1)} placeholder={t("admin.users.search")}/></div><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">{t("admin.common.allStatus")}</option><option value="active">{t("admin.status.active")}</option><option value="inactive">{t("admin.status.inactive")}</option><option value="blocked">{t("admin.status.blocked")}</option></select><button className="gls-admin-primary" onClick={()=>{setPage(1);void load()}}><Search size={16}/>{t("admin.common.search")}</button></div>
 {loading?<div className="gls-admin-loading">{t("admin.common.loading")}</div>:users.length===0?<div className="gls-admin-empty-v2">{t("admin.users.empty")}</div>:<div className="gls-admin-table-scroll"><table className="gls-admin-data-table"><thead><tr><th>{t("admin.users.profile")}</th><th>{t("admin.users.mobile")}</th><th>{t("admin.users.email")}</th><th>{t("admin.users.role")}</th><th>{t("admin.users.status")}</th><th>{t("admin.users.registered")}</th><th>{t("admin.users.actions")}</th></tr></thead><tbody>{users.map(u=><tr key={u._id||u.id}><td><div className="gls-user-cell"><div>{String(u.name||"?").slice(0,1)}</div><b>{u.name}</b></div></td><td>{u.mobile||"—"}</td><td>{u.email||"—"}</td><td>{u.role}</td><td><span className={`gls-pill ${u.status||"active"}`}>{u.status||"active"}</span></td><td>{u.createdAt?new Date(u.createdAt).toLocaleDateString():"—"}</td><td><div className="gls-row-actions">{u.role!=="admin"&&<><select className="gls-status-select" value={u.status||"active"} onChange={e=>void change(u._id,e.target.value)}><option value="active">{t("admin.status.active")}</option><option value="inactive">{t("admin.status.inactive")}</option><option value="blocked">{t("admin.status.blocked")}</option></select><button title={t("admin.users.delete")} onClick={()=>void del(u._id)}><Trash2 size={15}/></button></>}</div></td></tr>)}</tbody></table></div>}
 <div className="gls-admin-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>›</button></div>
 </section></div>
}
