import { useEffect, useState } from "react";
import { Plus, Pencil, Trash2, X, RefreshCw, Search } from "lucide-react";
import { useTranslation } from "react-i18next";
import { adminApi } from "../../lib/api";

const empty={name:"",district:"",subDistrict:"",taluka:"",address:"",phone:"",latitude:"",longitude:"",mapsUrl:""};
export default function AdminOffices(){
 const {t}=useTranslation();const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [q,setQ]=useState("");const [edit,setEdit]=useState<any|null>(null);const load=async()=>{setLoading(true);try{const r=await adminApi.offices();setItems(r.offices)}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const shown=items.filter(o=>`${o.name} ${o.district||""} ${o.subDistrict||o.taluka||""}`.toLowerCase().includes(q.toLowerCase()));
 const del=async(id:string)=>{if(confirm(t("admin.offices.confirmDelete"))){await adminApi.deleteOffice(id);void load()}};return <div><div className="gls-admin-page-title"><div><p>{t("admin.nav.offices")}</p><h1>{t("admin.offices.title")}</h1><span>{t("admin.offices.subtitle")}</span></div><button className="gls-admin-primary" onClick={()=>setEdit({})}><Plus size={17}/>{t("admin.offices.add")}</button></div><section className="gls-admin-card-v2"><div className="gls-admin-toolbar"><div className="gls-admin-searchbox"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t("admin.offices.search")}/></div><button className="gls-admin-refresh" onClick={()=>void load()}><RefreshCw size={16}/>{t("admin.common.refresh")}</button></div>{loading?<div className="gls-admin-loading">{t("admin.common.loading")}</div>:shown.length===0?<div className="gls-admin-empty-v2">{t("admin.offices.empty")}</div>:<div className="gls-admin-table-scroll"><table className="gls-admin-data-table"><thead><tr><th>{t("admin.offices.name")}</th><th>{t("admin.offices.district")}</th><th>{t("admin.offices.subDistrict")}</th><th>{t("admin.offices.address")}</th><th>{t("admin.offices.actions")}</th></tr></thead><tbody>{shown.map(o=><tr key={o._id}><td><b>{o.name}</b></td><td>{o.district||"—"}</td><td>{o.subDistrict||o.taluka||"—"}</td><td>{o.address||"—"}</td><td><div className="gls-row-actions"><button onClick={()=>setEdit(o)}><Pencil size={15}/></button><button onClick={()=>void del(o._id)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}</section>{edit!==null&&<OfficeModal t={t} value={{...empty,...edit}} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);void load()}}/>}</div>
}
function OfficeModal({t,value,onClose,onSaved}:{t:any;value:any;onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState(value);const [busy,setBusy]=useState(false);const save=async()=>{setBusy(true);try{const p={...f,latitude:f.latitude===""?undefined:Number(f.latitude),longitude:f.longitude===""?undefined:Number(f.longitude)};if(f._id)await adminApi.updateOffice(f._id,p);else await adminApi.createOffice(p);onSaved()}catch(e){alert(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};return <div className="gls-admin-modal-backdrop"><div className="gls-admin-modal"><div className="gls-admin-modal-head"><h2>{value._id?t("admin.offices.edit"):t("admin.offices.add")}</h2><button onClick={onClose}><X size={18}/></button></div><div className="gls-admin-form-grid">{Object.entries({name:t("admin.offices.name"),district:t("admin.offices.district"),subDistrict:t("admin.offices.subDistrict"),taluka:"Taluka",address:t("admin.offices.address"),phone:"Phone",latitude:"Latitude",longitude:"Longitude",mapsUrl:"Maps URL"}).map(([k,l])=><label key={k}><span>{l}</span><input value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><div className="gls-admin-modal-actions"><button onClick={onClose}>{t("admin.common.cancel")}</button><button className="gls-admin-primary" disabled={busy} onClick={()=>void save()}>{t("admin.common.save")}</button></div></div></div>}
