import { useRef, useState } from "react";
import { Camera, FileText, LogOut, MessageSquare, Save, UserCircle } from "lucide-react";
import { Link, useNavigate } from "react-router";
import { useTranslation } from "react-i18next";
import { authApi, fileUrl, uploadProfileImage } from "../../lib/api";
import { useAuthStore } from "./auth.store";

export default function ProfilePage(){ const {t}=useTranslation(); const nav=useNavigate(); const {token,user,setAuth,logout}=useAuthStore(); const [name,setName]=useState(user?.name||""); const [mobile,setMobile]=useState(user?.mobile||""); const [email,setEmail]=useState(user?.email||""); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(""); const ref=useRef<HTMLInputElement>(null);
 if(!token||!user){ nav("/login",{replace:true}); return null; }
 const upload=async(file:File)=>{try{const r=await uploadProfileImage(token,file);setAuth(token,r.user);setMsg(t("profile.imageSaved"));}catch(e){setMsg(e instanceof Error?e.message:"Error");}};
 const save=async()=>{setSaving(true);try{const r=await authApi.update(token,{name,mobile,email});setAuth(token,r.user);setMsg(t("profile.saved"));}catch(e){setMsg(e instanceof Error?e.message:"Error");}finally{setSaving(false)}};
 return <main className="gls-profile-page"><div className="gls-shell gls-profile-card"><div className="gls-profile-top"><div className="gls-profile-avatar">{user.profileImage?<img src={fileUrl(user.profileImage)} alt="Profile"/>:<UserCircle size={82}/>}<button type="button" onClick={()=>ref.current?.click()}><Camera size={15}/></button><input ref={ref} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></div><div><h1>{t("profile.title")}</h1><p>{t("profile.welcome")}, {user.name}</p><span className="gls-role">{user.role}</span></div></div><div className="gls-profile-form"><label>{t("auth.name")}<input value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("auth.mobile")}<input value={mobile} onChange={e=>setMobile(e.target.value)}/></label><label>{t("auth.email")}<input value={email} onChange={e=>setEmail(e.target.value)}/></label><button onClick={save} disabled={saving} className="gls-primary-btn"><Save size={16}/>{saving?t("auth.pleaseWait"):t("profile.save")}</button>{msg&&<p className="gls-login-notice">{msg}</p>}</div><div className="gls-profile-links"><Link to="/complaints"><MessageSquare size={18}/>{t("nav.complaints")}</Link><Link to="/documents"><FileText size={18}/>{t("nav.documents")}</Link><button onClick={()=>{logout();nav("/")}}><LogOut size={18}/>{t("profile.logout")}</button></div></div></main> }
